### ISSUE TITLE
Short the "spaghetti" code

### ISSUE THREAD

**Issue by wi110w** [VectorElk/euro_diffusion#2]
I would like to short it to this format:
`if 0 > countries_list[curr_country]["x1"] > constants.MAX_SIZE-1`
https://github.com/VectorElk/euro_diffusion/blob/37b7b295442ecede9222d63f2dc63b502624a673/eurodiff.py#L43-L50

**Comment by VectorElk** [comment]
Issue of "spaghetti" code is legit, but your code wouldn't work. i used
```not (0 <= countries_list[curr_country]["x1"] <= constants.MAX_SIZE-1)``` 
instead in 21f8d57018a211b24f1d6607e11468b0af9b11fe.

**Comment by cl0ne** [comment]
You can simplify code a little bit more by adding local variable for `countries_list[curr_country]`
