### ISSUE TITLE
Letters don't catched by ValueError

### ISSUE THREAD

**Issue by wi110w** [VectorElk/euro_diffusion#3]
On the test:
4
error k a 0 0
error2 k j -1 -1
error3 1 3 3 1
error4 1 3 2 1
0
**Expected:** ValueError catched error and the corresponding message about bad number of countries is displayed.
**Actual:** ValueError catched error and displayed own message: ValueError: invalid literal for int() with base 10: 'k'

**Comment by VectorElk** [comment]
Fixed in 21f8d57018a211b24f1d6607e11468b0af9b11fe.
